server:
  port: 8800

logging:
  path: logs
  file: mylog.log

spring:
  application:
    name: myTest
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/course?useSSL=false
      username: root
      password: Lx125634897

mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
   - mapper/*
