server:
  port: 8877

logging:
  path: logs
  file: mylog.log


spring:
  application:
    name: report
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/course?serverTimezone=GMT
    username: root
    password: Lx125634897

mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*
